baseURL = "https://example.com"
languageCode = "en-us"
paginate = 6.0
pygmentsstyle = "monokai"
theme = "novela"
title = "Hugo Novela"
[[menu.main]]
name = "About"
url = "/about/"
weight = 4
[[menu.main]]
name = "Videos"
url = "/videos/"
weight = 3
[[menu.main]]
identifier = "newsletter"
name = "Newsletter"
title = "All Newsletter"
url = "/newsletter/"
weight = 1
[[menu.main]]
identifier = "blog"
name = "Posts"
title = "All Posts"
url = "/post/"
weight = 2
[social]
dribbble = "#"
github = "#"
instagram = "#"
linkedin = "#"
twitter = "#"
youtube = "#"
[taxonomies]
author = "authors"
sectionPagesMenu = "main"
