baseURL = "https://example.com"
languageCode = "en-us"
title = "Hugo Novela"
pygmentsstyle = "monokai"
theme = "novela"
paginate = 6.0

[social]
twitter = "#"
github = "#"
instagram = "#"
linkedin = "#"
dribbble = "#"
youtube = "#"

[taxonomies]
author = "authors"

sectionPagesMenu = "main"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Posts"
    title = "All Posts"
    url = "/post/"
    weight = -110
  [[menu.main]]
    identifier = "newsletter"
    name = "Newsletter"
    title = "All Newsletter"
    url = "/newsletter/"
    weight = -110